import Head from 'next/head'
// import Image from 'next/image'
// import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          &lt;Hunting Coder/&gt;
        </h1>
        <div className={styles.image}>
          <img className={styles.coderImg} src="/coder.jpg" alt="This is an image"  width={237} height={158}/>
          {/* <Image className={styles.coderImg} src="/coder.jpg" alt="Picture of author" width={237} height={158} /> */}
        </div>

        <div>
          <h2 className={styles.h2}>Latest Blogs</h2>
          <h3>How to learn javascript in 2022</h3>
          <p>Javascript is the language used to design login for the web</p>
          <button className={styles.btn}>Read More</button>
        </div>
        <div>
          <h3>How to learn javascript in 2022</h3>
          <p>Javascript is the language used to design login for the web</p>
          <button className={styles.btn}>Read More</button>
        </div>
        <div>
          <h3>How to learn javascript in 2022</h3>
          <p>Javascript is the language used to design login for the web</p>
          <button className={styles.btn}>Read More</button>
        </div>
      </main>
    </div>
  )
}
